In [1]:
import pandas as pd
import networkx as nx
import random
import numpy as np

In [2]:
num_districts = 36

In [3]:
TX_data = pd.read_parquet('TX_data.parquet.gzip')

In [4]:
adj = pd.read_parquet('TX_adj.parquet.gzip').to_numpy()

In [5]:
adj

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [6]:
TX_data

CNTYVTD   VTD  WHITE  OTHER  HISPANIC  TOTPOP    VAP  BLACK  BLKHISP  \
0      10001  0001   2053     89       401    3131   2341    606      989   
1      10002  0002   3171     64       245    3744   2732    272      509   
2      10003  0003   1443     32       151    1766   1345    140      291   
3      10004  0004   1962     40        78    2147   1684     72      145   
4      10005  0005    454      2        14     476    366      6       20   
...      ...   ...    ...    ...       ...     ...    ...    ...      ...   
8936  990412  0412   3779    386       918    6051   4308   1053     1886   
8937  990413  0413   6682    193      2108   12005  11019   3041     5130   
8938  990414  0414    516      7        34     560    426      3       37   
8939  990415  0415    232      2        13     249    186      2       15   
8940  990416  0416   3173    353       849    5555   4025   1286     2029   

      WVAP  ...  USCD  SEND  HD  AREA PERIM        area_1      perimeter  \
0     1677  ...     5     3   8     6    15  5.616316e+06   15020.544928   
1     2365  ...     5     3   8   259    95  2.562133e+08   94432.828909   
2     1134  ...     5     3   8    72    55  7.084692e+07   55277.408937   
3     1553  ...     5     3   8   244    92  2.411696e+08   91313.174639   
4      349  ...     5     3   8   171    87  1.689853e+08   86938.250104   
...    ...  ...   ...   ...  ..   ...   ...           ...            ...   
8936  2827  ...    25    24  59    10    18  9.867536e+06   18064.345384   
8937  6027  ...    25    24  59   265   145  2.622444e+08  144655.769983   
8938   398  ...    25    24  59   208    64  2.060707e+08   63811.467811   
8939   178  ...    25    24  59    63    54  6.255085e+07   54133.335968   
8940  2468  ...    25    24  59    88    59  8.706169e+07   58833.303524   

            xcoord        ycoord    ID  
0     1.414807e+06  1.071494e+06     1  
1     1.414466e+06  1.055556e+06     2  
2     1.418575e+06  1.068586e+06     3  
3     1.429612e+06  1.063675e+06     4  
4     1.440459e+06  1.063028e+06     5  
...            ...           ...   ...  
8936  1.199263e+06  9.936886e+05  8937  
8937  1.209228e+06  1.032769e+06  8938  
8938  1.216184e+06  1.052612e+06  8939  
8939  1.203928e+06  1.048680e+06  8940  
8940  1.201676e+06  1.006656e+06  8941  

[8941 rows x 42 columns]

In [7]:
G = nx.from_numpy_matrix(adj)

In [8]:
edge_list = np.array(list(G.edges()))
a = np.array([[0, 1], [0, 2], [0, 5], [0, 567]])
a[:, 1]

array([  1,   2,   5, 567])

In [9]:
arr = np.array([0, 0, 1, 2, -1])
np.where(arr > 0)[0]

array([2, 3])

In [10]:
vert_pop = TX_data['TOTPOP'].to_numpy()
arr = [9, 90, 99, 990, 994]
a = np.array(arr)
sum(vert_pop[a])
np.append(a, [[1], [2]])

array([  9,  90,  99, 990, 994,   1,   2])

In [11]:
total_votes = sum(vert_pop)

In [12]:
for edge in G.edges():
    G[edge[0]][edge[1]]['weight'] = random.uniform(0, 1)

In [54]:
a = np.array([[0, 1, 3], [3, 45, 56], [57, 3, 9]])
b = np.array([0, 4, 78])
c = np.matmul(a, b)
c

array([ 238, 4548,  714])

T = nx.minimum_spanning_tree(G)
span_adj = nx.to_numpy_array

In [69]:
T = nx.minimum_spanning_tree(G) 
span_adj = nx.to_numpy_array(T)
temp = span_adj
span_adj

a = [0]*8941
x = np.array(a)
x[561] = 1

In [62]:
c_bool = True
while c_bool:
    y = x
    x = np.matmul(temp, x) + x
    x = np.array(x, dtype=bool)
    if np.array_equal(x, y):
        conn_bool = False
    

(array([557, 561]),)
(array([ 550,  556,  557,  561,  816, 1184]),)
(array([ 525,  548,  550,  553,  556,  557,  560,  561,  803,  816, 1184,
       1190, 3931, 3948, 6935]),)
(array([ 525,  548,  550,  553,  554,  555,  556,  557,  559,  560,  561,
        563,  803,  816, 1184, 1190, 3931, 3948, 6802, 6935, 6940]),)
(array([ 525,  548,  550,  552,  553,  554,  555,  556,  557,  559,  560,
        561,  562,  563,  803,  816, 1184, 1190, 3931, 3948, 6802, 6855,
       6874, 6896, 6935, 6940]),)
(array([ 525,  527,  548,  550,  552,  553,  554,  555,  556,  557,  559,
        560,  561,  562,  563,  568,  803,  816, 1184, 1190, 3931, 3948,
       6601, 6802, 6837, 6855, 6874, 6875, 6896, 6933, 6935, 6937, 6940]),)
(array([ 525,  526,  527,  548,  550,  552,  553,  554,  555,  556,  557,
        559,  560,  561,  562,  563,  565,  568,  571,  803,  816, 1184,
       1190, 3930, 3931, 3948, 3958, 6601, 6802, 6837, 6838, 6855, 6870,
       6874, 6875, 6896, 6933, 6935, 6937, 6938, 6940, 6

KeyboardInterrupt: 

In [80]:
a = np.array([0, 0, 0, 1, .4])
b = a

if a == b:
    print("k")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [14]:
num_edges = span_adj.shape[0]-1
span_edges_nodes = list(T.edges())
span_edges_nodes[0]

(0, 5)

In [15]:
possible_cuts = [i for i in range(0, 8941)]
cut_edges = [0]*35

In [16]:
for i in range(0, num_districts-1):
        r = random.randint(0, len(possible_cuts))
        remove_edge = possible_cuts[r]
        cut_edges[i] = remove_edge
        possible_cuts.remove(remove_edge)

In [17]:
r_vertex_1 = span_edges_nodes[cut_edges[0]][0]
r_vertex_2 = span_edges_nodes[cut_edges[0]][1]
r_vertex_1

295

In [18]:
 for i in range(0, num_districts-1):
        r_vertex_1 = span_edges_nodes[cut_edges[i]][0]
        r_vertex_2 = span_edges_nodes[cut_edges[i]][1]
        temp[r_vertex_1][r_vertex_2] = 0
        temp[r_vertex_2][r_vertex_1] = 0

In [19]:
r_vertex_1
r_vertex_2

8457

In [20]:
split = nx.from_numpy_matrix(temp)
split.number_of_nodes()

8941

In [21]:
nx.number_connected_components(split)

36

In [22]:
conn = nx.connected_components(split)
districts = []
for comp in conn:
    districts.append(list(comp))
districts

[[0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  81,
  82,
  83,
  85,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  109,
  186,
  187,
  188,
  189,
  199,
  205,
  221,
  222,
  223,
  224,
  225,
  242,
  243,
  244,
  248,
  249,
  250,
  256,
  257,
  259,
  260,
  261,
  262,
  263,
  264,
  265,
  266,
  267,
  268,
  269,
  270,
  271,
  272,
  273,
  274,
  275,
  276,
  277,
  278,
  279,
  280,
  281,
  282,
  283,
  284,
  285,
  286,
  287,
  288,
  289,
  290,
  291,
  292,
  293,
  294,
  296,
  297,
  

In [23]:
bins = []
for i in range(0, 8941):
    bins.append([i, 0])
bins

[[0, 0],
 [1, 0],
 [2, 0],
 [3, 0],
 [4, 0],
 [5, 0],
 [6, 0],
 [7, 0],
 [8, 0],
 [9, 0],
 [10, 0],
 [11, 0],
 [12, 0],
 [13, 0],
 [14, 0],
 [15, 0],
 [16, 0],
 [17, 0],
 [18, 0],
 [19, 0],
 [20, 0],
 [21, 0],
 [22, 0],
 [23, 0],
 [24, 0],
 [25, 0],
 [26, 0],
 [27, 0],
 [28, 0],
 [29, 0],
 [30, 0],
 [31, 0],
 [32, 0],
 [33, 0],
 [34, 0],
 [35, 0],
 [36, 0],
 [37, 0],
 [38, 0],
 [39, 0],
 [40, 0],
 [41, 0],
 [42, 0],
 [43, 0],
 [44, 0],
 [45, 0],
 [46, 0],
 [47, 0],
 [48, 0],
 [49, 0],
 [50, 0],
 [51, 0],
 [52, 0],
 [53, 0],
 [54, 0],
 [55, 0],
 [56, 0],
 [57, 0],
 [58, 0],
 [59, 0],
 [60, 0],
 [61, 0],
 [62, 0],
 [63, 0],
 [64, 0],
 [65, 0],
 [66, 0],
 [67, 0],
 [68, 0],
 [69, 0],
 [70, 0],
 [71, 0],
 [72, 0],
 [73, 0],
 [74, 0],
 [75, 0],
 [76, 0],
 [77, 0],
 [78, 0],
 [79, 0],
 [80, 0],
 [81, 0],
 [82, 0],
 [83, 0],
 [84, 0],
 [85, 0],
 [86, 0],
 [87, 0],
 [88, 0],
 [89, 0],
 [90, 0],
 [91, 0],
 [92, 0],
 [93, 0],
 [94, 0],
 [95, 0],
 [96, 0],
 [97, 0],
 [98, 0],
 [99, 0],
 [100, 0],

In [24]:
counter = 0
for comp in conn:
    for node in comp:
        bins[node][1] = counter
    counter += 1
bins

[[0, 0],
 [1, 0],
 [2, 0],
 [3, 0],
 [4, 0],
 [5, 0],
 [6, 0],
 [7, 0],
 [8, 0],
 [9, 0],
 [10, 0],
 [11, 0],
 [12, 0],
 [13, 0],
 [14, 0],
 [15, 0],
 [16, 0],
 [17, 0],
 [18, 0],
 [19, 0],
 [20, 0],
 [21, 0],
 [22, 0],
 [23, 0],
 [24, 0],
 [25, 0],
 [26, 0],
 [27, 0],
 [28, 0],
 [29, 0],
 [30, 0],
 [31, 0],
 [32, 0],
 [33, 0],
 [34, 0],
 [35, 0],
 [36, 0],
 [37, 0],
 [38, 0],
 [39, 0],
 [40, 0],
 [41, 0],
 [42, 0],
 [43, 0],
 [44, 0],
 [45, 0],
 [46, 0],
 [47, 0],
 [48, 0],
 [49, 0],
 [50, 0],
 [51, 0],
 [52, 0],
 [53, 0],
 [54, 0],
 [55, 0],
 [56, 0],
 [57, 0],
 [58, 0],
 [59, 0],
 [60, 0],
 [61, 0],
 [62, 0],
 [63, 0],
 [64, 0],
 [65, 0],
 [66, 0],
 [67, 0],
 [68, 0],
 [69, 0],
 [70, 0],
 [71, 0],
 [72, 0],
 [73, 0],
 [74, 0],
 [75, 0],
 [76, 0],
 [77, 0],
 [78, 0],
 [79, 0],
 [80, 0],
 [81, 0],
 [82, 0],
 [83, 0],
 [84, 0],
 [85, 0],
 [86, 0],
 [87, 0],
 [88, 0],
 [89, 0],
 [90, 0],
 [91, 0],
 [92, 0],
 [93, 0],
 [94, 0],
 [95, 0],
 [96, 0],
 [97, 0],
 [98, 0],
 [99, 0],
 [100, 0],

In [25]:

bins2 = []
for i in range(0, len(bins)):
    bins2.append(bins[i][1])
len(bins2)

8941

In [26]:
districts = []
for i in range(0, 36):
    districts.append([])
j_district = bins2[0]
districts[j_district].append(0)
districts

[[0],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 []]

In [27]:
districts = []
for i in range(0, 36):
    districts.append([])
counter = 0
for j in range(0, len(bins2)):
    j_district = bins2[j]
    districts[j_district].append(j)
    counter += 1
counter

8941

In [28]:
districts[0]

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [29]:
pop_total = 0
for i in range(0, num_districts):
    pop_total = 0
    for dist in districts[i]:
        pop_total += vert_pop[dist]
    districts[i] = [districts[i], len(districts[i]), pop_total]
    

In [30]:
pop = 0
for i in range(0, num_districts):
    pop += districts[i][2]

In [31]:
pop

25145561

In [32]:
for i in range(0, 36):
    if 8308 in districts[0][0]:
        print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35


In [33]:
t = [[]]*36

In [34]:
districts

[[[0,
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12,
   13,
   14,
   15,
   16,
   17,
   18,
   19,
   20,
   21,
   22,
   23,
   24,
   25,
   26,
   27,
   28,
   29,
   30,
   31,
   32,
   33,
   34,
   35,
   36,
   37,
   38,
   39,
   40,
   41,
   42,
   43,
   44,
   45,
   46,
   47,
   48,
   49,
   50,
   51,
   52,
   53,
   54,
   55,
   56,
   57,
   58,
   59,
   60,
   61,
   62,
   63,
   64,
   65,
   66,
   67,
   68,
   69,
   70,
   71,
   72,
   73,
   74,
   75,
   76,
   77,
   78,
   79,
   80,
   81,
   82,
   83,
   84,
   85,
   86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100,
   101,
   102,
   103,
   104,
   105,
   106,
   107,
   108,
   109,
   110,
   111,
   112,
   113,
   114,
   115,
   116,
   117,
   118,
   119,
   120,
   121,
   122,
   123,
   124,
   125,
   126,
   127,
   128,
   129,
   130,
   131,
   132,
   133,
   134,
   135,
   136,
   137,
   138

In [35]:
arr = [56, 47, 3333, 38]
max(arr)

3333

In [36]:
rand_dists = random.sample(range(0, num_districts), 2)
rand_dists

[34, 28]

In [37]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]]

In [38]:
arr = np.array(a)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [39]:
np.sign(sum(sum(arr[[0,3],:][:,[0,3]])))

1

In [40]:
np.sign(0)

0

In [41]:
one = [1, 2, 3, 4]
two = [5, 6, 7, 8]
three = [one, two]

In [42]:
three

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [43]:
one + two

[1, 2, 3, 4, 5, 6, 7, 8]

In [44]:
lst = []
lst.is_empty()

AttributeError: 'list' object has no attribute 'is_empty'

In [ ]:
if not len(lst):
    print("yes")

In [ ]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 4, 5, 8])
d = np.array([0, 0, 1, 3])
c = np.in1d(a, b).astype(int)
e = np.in1d(a, d).astype(int)

In [ ]:
np.where((np.where(a == d, 1, 0))==1)

In [ ]:
a = np.array([-1, 2, 3, 4])
b = np.array([0, 3, 4, -90])

In [ ]:
pop_diff = abs(a-b)
m = min(pop_diff)
np.where(pop_diff == m)[0][0]

In [ ]:
possible_cuts = np.array([i for i in range(0, 56)])
r = random.randint(0, len(possible_cuts))
remove_edge = possible_cuts[r]
remove_edge

In [ ]:
random.randint(0, len(possible_cuts))

In [ ]:
a = np.array([0, 4, 484848, 4748])
idx = np.where(a == 4748)[0][0]
idx

In [ ]:
print("possible cuts: ", possible_cuts)